-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.0.21-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             11.3.0.6295
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping structure for table peq.rule_values
CREATE TABLE IF NOT EXISTS `rule_values` (
  `ruleset_id` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `rule_name` varchar(64) NOT NULL DEFAULT '',
  `rule_value` varchar(30) NOT NULL DEFAULT '',
  `notes` longtext,
  PRIMARY KEY (`ruleset_id`,`rule_name`),
  KEY `ruleset_id` (`ruleset_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table peq.rule_values: ~584 rows (approximately)
/*!40000 ALTER TABLE `rule_values` DISABLE KEYS */;
INSERT INTO `rule_values` (`ruleset_id`, `rule_name`, `rule_value`, `notes`) VALUES
	(1, 'AA:ExpPerPoint', '23976503', 'Amount of experience per AA. Is the same as the amount of experience to go from level 51 to level 52'),
	(1, 'AA:ModernAAScalingAALimit', '4000', 'The number of earned AA when AA experience scaling ends'),
	(1, 'AA:ModernAAScalingAAMinimum', '0', 'The minimum number of earned AA before AA experience scaling begins'),
	(1, 'AA:ModernAAScalingEnabled', 'false', 'Are we linearly scaling AA experience based on total # of earned AA?'),
	(1, 'AA:ModernAAScalingStartPercent', '1000.0000000000000', '1000% or 10x AA experience at the start of the scaling range'),
	(1, 'AA:NormalizedAAEnabled', 'false', 'TSS+ change to AA that normalizes AA experience to a fixed # of white con kills independent of level'),
	(1, 'AA:NormalizedAANumberOfWhiteConPerAA', '25', 'The number of white con kills per AA point'),
	(1, 'AA:SoundForAAEarned', 'FALSE', 'Play sound when AA point earned'),
	(1, 'Adventure:DistanceForRescueAccept', '10000.0000000000000', 'Distance for adventure rescue accept'),
	(1, 'Adventure:DistanceForRescueComplete', '2500.0000000000000', 'Distance for adventure rescue complete'),
	(1, 'Adventure:ItemIDToEnablePorts', '41000', 'ItemID to enable adventure ports. 0 to disable, otherwise using a LDoN portal will require the user to have this item'),
	(1, 'Adventure:LDoNBaseTrapDifficulty', '15.0000000000000', 'LDoN base trap difficulty'),
	(1, 'Adventure:LDoNCriticalFailTrapThreshold', '10.0000000000000', 'LDoN critical fail trap threshold'),
	(1, 'Adventure:LDoNTrapDistanceUse', '625', 'LDoN trap distance use'),
	(1, 'Adventure:MaxLevelRange', '9', 'Maximum level range for adventure'),
	(1, 'Adventure:MaxNumberForGroup', '6', 'Maximum members for adventure group'),
	(1, 'Adventure:MinNumberForGroup', '2', 'Minimum members for adventure group'),
	(1, 'Adventure:NumberKillsForBossSpawn', '40', 'Number of adventure kills to make the boss spawn'),
	(1, 'Aggro:AggroPlayerPets', 'false', 'If enabled, NPCs will aggro player pets'),
	(1, 'Aggro:AllowTickPulling', 'true', 'tick pulling is an exploit in an NPC\'s call for help fixed sometime in 2006 on live'),
	(1, 'Aggro:ClientAggroCheckIdleInterval', '6000', 'Interval in which clients actually check for aggro while idle - in milliseconds - this should be higher than ClientAggroCheckMovingInterval'),
	(1, 'Aggro:ClientAggroCheckMovingInterval', '1000', 'Interval in which clients actually check for aggro while moving - in milliseconds - this should be lower than ClientAggroCheckIdleInterval'),
	(1, 'Aggro:CriticallyWoundedAggroMod', '100', 'Aggro increase against critical wounded targets'),
	(1, 'Aggro:CurrentTargetAggroMod', '0', 'Aggro increase against current target. 0% = prefer the current target to any other. Makes it harder for our NPC to switch targets'),
	(1, 'Aggro:IntAggroThreshold', '75', 'Int lesser or equal the value will aggro regardless of level difference'),
	(1, 'Aggro:MaxScalingProcAggro', '400', 'Set to -1 for no limit. Maximum amount of aggro that HP scaling SPA effect in a proc will add'),
	(1, 'Aggro:MeleeRangeAggroMod', '20', 'Aggro increase against targets in melee range. 10=10%'),
	(1, 'Aggro:MinAggroLevel', '18', 'Minimum level for use with UseLevelAggro'),
	(1, 'Aggro:NPCAggroMaxDistanceEnabled', 'false', 'If enabled, NPC\'s will drop aggro beyond 600 units or what is defined at the zone level'),
	(1, 'Aggro:PetAttackRange', '40000.0000000000000', 'Maximum squared range /pet attack works at default is 200'),
	(1, 'Aggro:PetSpellAggroMod', '10', 'Aggro increase for pet spells'),
	(1, 'Aggro:SittingAggroMod', '35', 'Aggro increase against sitting targets. 35=35%'),
	(1, 'Aggro:SmartAggroList', 'true', 'Smart aggro list attempts to choose targets in a much smarter fashion, prefering players to pets, sitting and critically injured players to normal players, and players in melee range to players not'),
	(1, 'Aggro:SpellAggroMod', '100', 'Aggro increase for spells'),
	(1, 'Aggro:TunnelVisionAggroMod', '0.7500000000000', 'People not currently the top hate generate this much hate on a Tunnel Vision mob'),
	(1, 'Aggro:UseLevelAggro', 'true', 'MinAggroLevel rule value+ and Undead will aggro regardless of level difference. This will disabled Rule:IntAggroThreshold if set to true'),
	(1, 'Bazaar:AuditTrail', 'false', 'Setting whether a path to the trader should be displayed in the bazaar'),
	(1, 'Bazaar:EnableWarpToTrader', 'true', 'Setting whether teleport to the selected trader should be active'),
	(1, 'Bazaar:MaxBarterSearchResults', '200', 'The maximum results returned in the /barter search'),
	(1, 'Bazaar:MaxSearchResults', '200', 'Maximum number of search results in Bazaar'),
	(1, 'Bugs:DumpTargetEntity', 'false', 'Dumps the target entity, if one is provided'),
	(1, 'Bugs:ReportingSystemActive', 'true', 'Activates bug reporting'),
	(1, 'Bugs:UseOldReportingMethod', 'true', 'Forces the use of the old bug reporting system'),
	(1, 'Channels:DeleteTimer', '1440', 'Empty password protected channels will be deleted after this many minutes'),
	(1, 'Channels:RequiredStatusAdmin', '251', 'Required status to administer chat channels'),
	(1, 'Channels:RequiredStatusListAll', '251', 'Required status to list all chat channels'),
	(1, 'Character:AAExpMultiplier', '0.6499999761581', 'If greater than 0, the AA experience gained is multiplied by this value. '),
	(1, 'Character:ActiveInvSnapshots', 'false', 'Takes a periodic snapshot of inventory contents from online players'),
	(1, 'Character:AllowCrossClassTrainers', 'false', 'If the value is true, a player can also train with other class Guildmasters.'),
	(1, 'Character:AllowMQTarget', 'false', 'Disables putting players in the \'hackers\' list for targeting beyond the clip plane or attempting to target something untargetable'),
	(1, 'Character:AutosaveIntervalS', '300', 'Number of seconds after which a timer is triggered which stores the character data. The value 0 means no periodic automatic saving.'),
	(1, 'Character:AvoidanceCap', '750', '750 Is a pretty good value, seen people dodge all attacks beyond 1,000 Avoidance'),
	(1, 'Character:BaseHPRegenBonusRaces', '4352', 'A bitmask of race(s) that receive the regen bonus. Iksar (4096) & Troll (256) = 4352. See common/races.h for the bitmask values'),
	(1, 'Character:BaseInstrumentSoftCap', '36', 'Softcap for instrument mods, 36 commonly referred to as 3.6 as well'),
	(1, 'Character:BaseRunSpeedCap', '158', 'Base Run Speed Cap, on live it\'s 158% which will give you a runspeed of 1.580 hard capped to 225'),
	(1, 'Character:BindAnywhere', 'false', 'Allows players to bind their soul anywhere in the world'),
	(1, 'Character:BlueModifier', '25', 'The experience obtained for blue con mobs is multiplied by value/100'),
	(1, 'Character:CheckCursorEmptyWhenLooting', 'false', 'If true, a player cannot loot a corpse (player or NPC) with an item on their cursor'),
	(1, 'Character:CorpseDecayTimeMS', '650327041', 'Time after which the corpse decays (milliseconds)'),
	(1, 'Character:CorpseResTimeMS', '10800000', 'Time after which the corpse can no longer be resurrected (milliseconds)'),
	(1, 'Character:DeathExpLossLevel', '6', 'Any level equal to or greater than this will lose experience at death'),
	(1, 'Character:DeathExpLossMaxLevel', '255', 'Every higher level will no longer lose experience at death'),
	(1, 'Character:DeathExpLossMultiplier', '0', 'Adjust how much experience is lost. Default 3.5% (0=0.5%, 1=1.5%, 2=2.5%, 3=3.5%, 4=4.5%, 5=5.5%, 6=6.5%, 7=7.5%, 8=8.5%, 9=9.5%, 10=11%)'),
	(1, 'Character:DeathItemLossLevel', '1', 'From this level on, items are left in the corpse when LeaveCorpses is activated'),
	(1, 'Character:DefaultGuild', '1', 'If not 0, new characters placed into the guild # indicated'),
	(1, 'Character:DismountWater', 'true', 'Dismount horses when entering water'),
	(1, 'Character:DragCorpseDistance', '400.0000000000000', 'If a player is using /corpsedrag and moving, the corpse will not move until the player exceeds this distance'),
	(1, 'Character:EnableAggroMeter', 'true', 'Enable Aggro Meter, for users with RoF and later clients'),
	(1, 'Character:EnableAvoidanceCap', 'false', 'Setting whether the avoidance cap should be activated'),
	(1, 'Character:EnableCharacterEXPMods', 'false', 'Enables character zone-based experience modifiers.'),
	(1, 'Character:EnableDiscoveredItems', 'true', 'If enabled, it enables EVENT_DISCOVER_ITEM and also saves character names and timestamps for the first time an item is discovered'),
	(1, 'Character:EnableFoodRequirement', 'TRUE', 'If disabled, food is no longer required'),
	(1, 'Character:EnableHungerPenalties', 'true', 'Being hungry/thirsty has negative effects -- it does appear normal live servers do not have penalties'),
	(1, 'Character:EnableTestBuff', 'false', 'Allow the use of /testbuff'),
	(1, 'Character:EnableXTargetting', 'false', 'Enable Extended Targeting Window, for users with UF and later clients'),
	(1, 'Character:EnduranceRegenMultiplier', '100', 'The endurance regeneration is multiplied by value/100 (up to the caps)'),
	(1, 'Character:EnvironmentDamageMulipliter', '1.0000000000000', 'Multiplier for environmental damage like fall damage.'),
	(1, 'Character:ExpMultiplier', '1.5000000000000', 'If greater than 0, the experience gained is multiplied by this value. '),
	(1, 'Character:FeignKillsPet', 'false', 'Setting whether Feign Death kills the player pet'),
	(1, 'Character:FinalExpMultiplier', '1.0000000000000', 'Added on top of everything else, easy for setting EXP events'),
	(1, 'Character:FoodLossPerUpdate', '35', 'How much food/water you lose per stamina update'),
	(1, 'Character:GrantHoTTOnCreate', 'false', 'Grant Health of Target\'s Target leadership AA on character creation'),
	(1, 'Character:GreenModifier', '15', 'The experience obtained for green con mobs is multiplied by value/100'),
	(1, 'Character:GroupExpMultiplier', '1.0000000000000', 'The experience in a group is multiplied by this value in addition to the group multiplier. The group multiplier is: 2 members=x 1.2, 3=x1.4, 4=x1.6, 5=x1.8, 6=x2.16'),
	(1, 'Character:HasteCap', '100', 'Haste cap for non-v3(over haste) haste'),
	(1, 'Character:HealOnLevel', 'false', 'Setting whether a player should heal completely when leveling'),
	(1, 'Character:HPRegenMultiplier', '100', 'The hitpoint regeneration is multiplied by value/100 (up to the caps)'),
	(1, 'Character:IksarCommonTongue', '95', 'Starting value for Common Tongue for Iksars'),
	(1, 'Character:InvSnapshotHistoryD', '30', 'Time to keep snapshot entries (days)'),
	(1, 'Character:InvSnapshotMinIntervalM', '180', 'Minimum time between inventory snapshots (minutes)'),
	(1, 'Character:InvSnapshotMinRetryM', '30', 'Time to re-attempt an inventory snapshot after a failure  (minutes)'),
	(1, 'Character:ItemAccuracyCap', '150', 'Limit on accuracy granted by items'),
	(1, 'Character:ItemATKCap', '250', 'Limit on ATK granted by items'),
	(1, 'Character:ItemAvoidanceCap', '100', 'Limit on avoidance granted by items'),
	(1, 'Character:ItemCastsUseFocus', 'true', 'If true, this allows item clickies to use focuses that have limited maximum levels on them'),
	(1, 'Character:ItemClairvoyanceCap', '250', 'Limit on clairvoyance granted by items'),
	(1, 'Character:ItemCombatEffectsCap', '100', 'Limit on combat effects granted by items'),
	(1, 'Character:ItemDamageShieldCap', '30', 'Limit on damage shields granted by items'),
	(1, 'Character:ItemDoTShieldingCap', '35', 'Limit on DoT shielding granted by items'),
	(1, 'Character:ItemDSMitigationCap', '50', 'Limit on damageshield mitigation granted by items'),
	(1, 'Character:ItemEnduranceRegenCap', '15', 'Limit on endurance regeneration granted by items'),
	(1, 'Character:ItemExtraDmgCap', '150', 'Cap for bonuses to melee skills like Bash, Frenzy, etc.'),
	(1, 'Character:ItemHealAmtCap', '250', 'Limit on heal amount granted by items'),
	(1, 'Character:ItemHealthRegenCap', '15', 'Limit on health regeneration granted by items'),
	(1, 'Character:ItemManaRegenCap', '15', 'Limit on mana regeneration granted by items'),
	(1, 'Character:ItemShieldingCap', '35', 'Limit on shielding granted by items'),
	(1, 'Character:ItemSpellDmgCap', '250', 'Limit on spell damage granted by items'),
	(1, 'Character:ItemSpellShieldingCap', '35', 'Limit on spell shielding granted by items'),
	(1, 'Character:ItemStrikethroughCap', '35', 'Limit on strikethrough granted by items'),
	(1, 'Character:ItemStunResistCap', '200', 'Limit on resistance granted by items'),
	(1, 'Character:KeepLevelOverMax', 'false', 'Don\'t de-level a character that has somehow gone over the level cap'),
	(1, 'Character:KillsPerGroupLeadershipAA', '250', 'Minimum number of dark blue mobs that must be killed to get a Group Leadership AA'),
	(1, 'Character:KillsPerRaidLeadershipAA', '250', 'Minimum number of dark blue mobs that must be killed to get a Raid Leadership AAA'),
	(1, 'Character:LeaveCorpses', 'true', 'Setting whether you leave a corpse behind'),
	(1, 'Character:LeaveNakedCorpses', 'false', 'Setting whether you leave a corpse without items'),
	(1, 'Character:LightBlueModifier', '20', 'The experience obtained for light-blue con mobs is multiplied by value/100'),
	(1, 'Character:MaintainIntoxicationAcrossZones', 'false', 'If true, alcohol effects are maintained across zoning and logging out/in'),
	(1, 'Character:ManaOnLevel', 'false', 'Restore player\'s full mana on level up'),
	(1, 'Character:ManaRegenMultiplier', '100', 'The mana regeneration is multiplied by value/100 (up to the caps)'),
	(1, 'Character:MarqueeHPUpdates', 'false', 'Will show health percentage in center of screen if health lesser than 100%'),
	(1, 'Character:MaxCharmDurationForPlayerCharacter', '15', 'Maximum number of tics a player can be charmed. 1 tic equls 6 seconds'),
	(1, 'Character:MaxDraggedCorpses', '2', 'Maximum number of corpses you can drag at once'),
	(1, 'Character:MaxExpLevel', '50', 'Defines the maximum level that can be reached through experience'),
	(1, 'Character:MaxFearDurationForPlayerCharacter', '0', 'Maximum number of tics a player can be feared. 1 tic equls 6 seconds'),
	(1, 'Character:MaxLevel', '50', 'Sets the highest level for players that can be reached through experience'),
	(1, 'Character:MinStatusForNoDropExemptions', '80', 'This allows status x and higher to trade no drop items'),
	(1, 'Character:OgreCommonTongue', '95', 'Starting value for Common Tongue for Ogres'),
	(1, 'Character:OldMinMana', 'true', 'This is used for servers that want to follow older skill cap formulas so they can still have some regen w/o mediate'),
	(1, 'Character:OPClientUpdateVisualDebug', 'false', 'Shows a pulse and forward directional particle each time the client sends its position to server'),
	(1, 'Character:OrnamentationAugmentType', '20', 'Ornamentation Augment Type'),
	(1, 'Character:PerCharacterBucketMaxLevel', 'false', 'Check for data bucket \'CharMaxLevel\', if player tries to level beyond that point, it will not go beyond that level'),
	(1, 'Character:PerCharacterQglobalMaxLevel', 'false', 'Check for qglobal \'CharMaxLevel\' character qglobal (Type 5, ""), if player tries to level beyond that point, it will not go beyond that level'),
	(1, 'Character:PetsUseReagents', 'true', 'Conjuring pets consumes reagents'),
	(1, 'Character:ProcessFearedProximity', 'FALSE', 'Processes proximity checks when feared'),
	(1, 'Character:PVPEnableGuardFactionAssist', 'true', 'Enables faction based assisting against the aggresor in pvp.'),
	(1, 'Character:RaidExpMultiplier', '0.2000000029802', 'The experience gained in raids is multiplied by (1-RaidExpMultiplier) '),
	(1, 'Character:RedModifier', '50', 'The experience obtained for red con mobs is multiplied by value/100'),
	(1, 'Character:RespawnFromHover', 'false', 'Setting whether the respawn window should be used'),
	(1, 'Character:RespawnFromHoverTimer', '300', 'Respawn Window countdown timer, in seconds'),
	(1, 'Character:RestRegenEnabled', 'false', 'Setting to activate out-of-combat regeneration'),
	(1, 'Character:RestRegenRaidTimeToActivate', '180', 'Time in seconds for rest state regen to kick in with a raid target'),
	(1, 'Character:RestRegenTimeToActivate', '20', 'Time in seconds for rest state regen to kick in'),
	(1, 'Character:RestrictSpellScribing', 'true', 'Setting whether to restrict spell scribing to allowable races/classes of spell scroll'),
	(1, 'Character:SharedBankPlat', 'true', 'Shared bank platinum. Off by default to prevent duplication'),
	(1, 'Character:ShowExpValues', '0', 'Show experience values. 0=normal, 1=show raw experience values, 2=show raw experience values and percent'),
	(1, 'Character:SkillCapMaxLevel', '-1', 'Sets the Maximum Level used for Skill Caps (from skill_caps table). -1 makes it use MaxLevel rule value. It is set to 75 because PEQ only has skill caps up to that level, and grabbing the players\' skill past 75 will return 0, breaking all skills past that level. This helps servers with obsurd level caps (75+ level cap) function without any modifications'),
	(1, 'Character:SkillUpFromItems', 'true', 'Allow Skill ups from clickable items'),
	(1, 'Character:SkillUpModifier', '300', 'The probability for a skill-up is multiplied by value/100'),
	(1, 'Character:SoDClientUseSoDHPManaEnd', 'true', 'Setting this to true will allow SoD clients to use the SoD HP/Mana/End formulas and previous clients will use the old formulas'),
	(1, 'Character:SoftDeletes', 'TRUE', 'When characters are deleted in character select, they are only soft deleted'),
	(1, 'Character:StatCap', '0', 'If StatCap > 0 then this value is used. If it is 0, the value of the following code is used: If Level < 61: 255. If Level >= 61 and the client SoF or newer: 255 + 5 x (level -60).  If the client is older than SoF and the level < 71 then: 255 + x (level-60). In all other cases: 330.'),
	(1, 'Character:TradeskillUpAlchemy', '2', 'Alchemy skillup rate adjustment. Lower is faster'),
	(1, 'Character:TradeskillUpBaking', '2', 'Baking skillup rate adjustment. Lower is faster'),
	(1, 'Character:TradeskillUpBlacksmithing', '2', 'Blacksmithing skillup rate adjustment. Lower is faster'),
	(1, 'Character:TradeskillUpBrewing', '3', 'Brewing skillup rate adjustment. Lower is faster'),
	(1, 'Character:TradeskillUpFletching', '2', 'Fletching skillup rate adjustment. Lower is faster'),
	(1, 'Character:TradeskillUpJewelcrafting', '2', 'Jewelcrafting skillup rate adjustment. Lower is faster'),
	(1, 'Character:TradeskillUpMakePoison', '2', 'Make Poison skillup rate adjustment. Lower is faster'),
	(1, 'Character:TradeskillUpPottery', '4', 'Pottery skillup rate adjustment. Lower is faster'),
	(1, 'Character:TradeskillUpResearch', '1', 'Research skillup rate adjustment. Lower is faster'),
	(1, 'Character:TradeskillUpTinkering', '2', 'Tinkering skillup rate adjustment. Lower is faster'),
	(1, 'Character:TrollCommonTongue', '95', 'Starting value for Common Tongue for Trolls'),
	(1, 'Character:UnmemSpellsOnDeath', 'true', 'Setting whether at death all memorized Spells are forgotten'),
	(1, 'Character:UseDeathExpLossMult', 'true', 'Setting to control whether DeathExpLossMultiplier or the code default is used: (Level x Level / 18.0) x 12000'),
	(1, 'Character:UseNewStatsWindow', 'false', 'Setting whether the new Stats window, which displays all information, should be used'),
	(1, 'Character:UseNoJunkFishing', 'FALSE', 'Disregards junk items when fishing'),
	(1, 'Character:UseOldBindWound', 'true', 'Uses the original bind wound behavior'),
	(1, 'Character:UseOldClassExpPenalties', 'true', 'Setting this to true will enable old class experience penalties for Paladin, SK, Ranger, Bard, Monk, Wizard, Enchanter, Magician, and Necromancer, as well as the bonus for Rogues and Warriors'),
	(1, 'Character:UseOldConSystem', 'true', 'Setting whether the pre SoF era consider system should be used'),
	(1, 'Character:UseOldRaceExpPenalties', 'true', 'Setting this to true will enable racial experience penalties for Iksar, Troll, Ogre, and Barbarian, as well as the bonus for Halflings'),
	(1, 'Character:UseOldRaceRezEffects', 'true', 'Older clients had ID 757 for races with high starting STR, but it doesn\'t seem used anymore'),
	(1, 'Character:UseRaceClassExpBonuses', 'true', 'Setting this to true will enable Class and Racial experience rate bonuses'),
	(1, 'Character:UseSpellFileSongCap', 'true', 'When they removed the AA that increased the cap they removed the above and just use the spell field'),
	(1, 'Character:UseStackablePickPocketing', 'true', 'Allows stackable pickpocketed items to stack instead of only being allowed in empty inventory slots'),
	(1, 'Character:UseXPConScaling', 'true', 'When activated, the experience is modified depending on the difference between player level and NPC level. The values from the rules GreenModifier to RedModifier are used'),
	(1, 'Character:WhiteModifier', '30', 'The experience obtained for white con mobs is multiplied by value/100'),
	(1, 'Character:YellowModifier', '40', 'The experience obtained for yellow con mobs is multiplied by value/100'),
	(1, 'Chat:EnableAntiSpam', 'true', 'Enable anti-spam system for chat'),
	(1, 'Chat:EnableMailKeyIPVerification', 'true', 'Setting whether the authenticity of the client should be verified via its IP address when accessing the InGame mailbox'),
	(1, 'Chat:EnableVoiceMacros', 'true', 'Enable voice macros'),
	(1, 'Chat:GlobalChatLevelLimit', '1', 'Level limit you need to of reached to talk in ooc/auction/chat if your karma is too low'),
	(1, 'Chat:IntervalDurationMS', '60000', 'Interval length in milliseconds'),
	(1, 'Chat:KarmaGlobalChatLimit', '72', 'Amount of karma you need to be able to talk in ooc/auction/chat below the level limit'),
	(1, 'Chat:KarmaUpdateIntervalMS', '1200000', 'Karma update interval in milliseconds'),
	(1, 'Chat:MaximumMessagesPerInterval', '50', 'Maximum value of chat messages allowed per interval'),
	(1, 'Chat:MaxMessagesBeforeKick', '60', 'If an attempt is made to send more than the maximum allowed number of chat messages per interval, the client will be disconnected after this absolute number of messages'),
	(1, 'Chat:MinimumMessagesPerInterval', '4', 'Minimum number of chat messages allowed per interval. The karma value is added to this value'),
	(1, 'Chat:MinStatusToBypassAntiSpam', '80', 'Minimum status to bypass the anti-spam system'),
	(1, 'Chat:ServerWideAuction', 'false', 'Enable server wide auction-chat'),
	(1, 'Chat:ServerWideOOC', 'false', 'Enable server wide ooc-chat'),
	(1, 'Chat:SuppressCommandErrors', 'true', 'Do not suppress command errors by default'),
	(1, 'Client:UseLiveBlockedMessage', 'true', 'Setting whether detailed spell block messages should be used as on the live servers'),
	(1, 'Client:UseLiveFactionMessage', 'true', 'Allows players to see detailed faction adjustments as on the live servers'),
	(1, 'Combat:AAMitigationACFactor', '3.0000000000000', 'If OldACSoftcapRules: AA mitgation armorclass factor'),
	(1, 'Combat:ACthac0Factor', '0.5500000119209', 'If a mob is attacked and the attack roll is greater than his defense roll, the attack rating is multiplied by this value'),
	(1, 'Combat:ACthac20Factor', '0.5500000119209', 'If a mob is attacked and his defense roll is greater than the attack roll, the attack rating is multiplied by this value'),
	(1, 'Combat:AdjustProcPerMinute', 'true', 'Adapt the average proc rate to the speed of the weapon'),
	(1, 'Combat:AERampageSafeZone', '0.0179999992251', 'max hit ae ramp reduction range'),
	(1, 'Combat:AgiHitFactor', '0.0099999997765', 'Factor with which agility is taken into account in the hit probability. Higher is better'),
	(1, 'Combat:ArcheryBonusRequiresStationary', 'true', 'does the 2x archery bonus chance require a stationary npc'),
	(1, 'Combat:ArcheryCritDifficulty', '3400', 'Value against which is rolled to check if an archery crit is triggered. Lower is easier'),
	(1, 'Combat:ArcheryHitPenalty', '0.2500000000000', 'Archery has a hit penalty to try to help balance it with the plethora of long term +hit modifiers for it'),
	(1, 'Combat:ArcheryNPCMultiplier', '1.0000000000000', 'Value is multiplied by the regular dmg to get the archery dmg'),
	(1, 'Combat:AssistNoTargetSelf', 'true', 'When assisting a target that does not have a target: true = target self, false = leave target as was before assist (false = live like)'),
	(1, 'Combat:AvgDefProcsPerMinute', '2.0000000000000', 'Average defense procs per minute'),
	(1, 'Combat:AvgProcsPerMinute', '2.0000000000000', 'Average proc rate per minute'),
	(1, 'Combat:BaseHitChance', '89.0000000000000', 'Base chance to hit'),
	(1, 'Combat:BaseProcChance', '0.0350000001490', 'Base chance for procs'),
	(1, 'Combat:BerserkerFrenzyEnd', '45', 'Percentage Health Points above which Warrior and Berserker end frenzy'),
	(1, 'Combat:BerserkerFrenzyStart', '35', 'Percentage Health Points below which Warrior and Berserker start frenzy'),
	(1, 'Combat:CasterACSoftcapReturn', '0.0599999986589', 'If OldACSoftcapRules: WIZ/MAG/NEC/ENC/DRU armorclass softcap increase-factor'),
	(1, 'Combat:ChainACSoftcap', '200', 'If OldACSoftcapRules is true: armorclass softcap for chain armor'),
	(1, 'Combat:Classic2HBAnimation', 'false', '2HB will use the 2 hand piercing animation instead of the overhead slashing animation'),
	(1, 'Combat:ClassicMasterWu', 'true', 'Classic Master Wu uses a random special, modern doesn\'t'),
	(1, 'Combat:ClassicNPCBackstab', 'true', 'True disables NPC facestab - NPC get normal attack if not behind'),
	(1, 'Combat:ClothACSoftcap', '75', 'If OldACSoftcapRules is true: armorclass softcap for cloth armor'),
	(1, 'Combat:ClrRngMnkBrdACSoftcapReturn', '0.3030000030994', 'CLR/RNG/MNK/BRD armorclass softcap increase-factor'),
	(1, 'Combat:DefaultRampageTargets', '1', 'Default number of people to hit with rampage'),
	(1, 'Combat:DefProcPerMinAgiContrib', '0.0750000029802', 'How much agility contributes to defensive proc rate'),
	(1, 'Combat:DruNecWizEncMagACSoftcapReturn', '0.2000000029802', 'DRU/NEC/WIZ/ENC/MAG softcap increase-factor'),
	(1, 'Combat:EnableFearPathing', 'true', 'Setting whether to use pathing during fear'),
	(1, 'Combat:EnableSneakPull', 'false', 'Enable implementation of Sneak Pull'),
	(1, 'Combat:EXPFromDmgShield', 'false', 'Determine if damage from a damage shield counts for experience gain'),
	(1, 'Combat:FleeGray', 'true', 'If true FleeGrayHPRatio will be used'),
	(1, 'Combat:FleeGrayHPRatio', '20', 'HP percentage when a Gray NPC begins to flee'),
	(1, 'Combat:FleeGrayMaxLevel', '18', 'NPC above this level won\'t do gray/green con flee'),
	(1, 'Combat:FleeHPRatio', '20', 'HP percentage when a NPC begins to flee'),
	(1, 'Combat:FleeIfNotAlone', 'false', 'If false, mobs won\'t flee if other mobs are in combat with it'),
	(1, 'Combat:HitBonusPerLevel', '1.2000000476837', 'You gain this percentage of hit for every level you are above your target'),
	(1, 'Combat:HitBoxMod', '1.0000000000000', 'Added to test hit boxes.'),
	(1, 'Combat:HitCapPre10', '20', 'Hit cap before  level 10. Live has it capped at 20'),
	(1, 'Combat:HitCapPre20', '40', 'Hit cap before  level 20. Live has it capped at 40'),
	(1, 'Combat:HitFalloffMajor', '50.0000000000000', 'Hit will fall off sharply if we\'re outside the minor and moderate range'),
	(1, 'Combat:HitFalloffMinor', '5.0000000000000', 'Hit will fall off up to value over the initial level range (percent)'),
	(1, 'Combat:HitFalloffModerate', '7.0000000000000', 'Hit will fall off up to value over the three levels after the initial level range (percent)'),
	(1, 'Combat:KnightACSoftcapReturn', '0.3300000131130', 'If OldACSoftcapRules: SHD/PAL/MNK armorclass softcap increase-factor'),
	(1, 'Combat:LeatherACSoftcap', '100', 'If OldACSoftcapRules is true: armorclass softcap for leather armor'),
	(1, 'Combat:LevelToStopACTwinkControl', '50', 'Level to stop armorclass twink control. 1 will effectively disable it, 50 should give basically same results as current system'),
	(1, 'Combat:LevelToStopDamageCaps', '0', 'Level to stop damage caps. 1 will effectively disable them, 20 should give basically same results as old incorrect system'),
	(1, 'Combat:LowChainLeatherACSoftcapReturn', '0.1700000017881', 'If OldACSoftcapRules: RNG/BST armorclass softcap increase-factor'),
	(1, 'Combat:LowPlateChainACSoftcapReturn', '0.2300000041723', 'If OldACSoftcapRules: CLR/BRD/BSK/ROG/SHA/MNK armorclass softcap increase-factor'),
	(1, 'Combat:MaxChancetoHit', '100.0000000000000', 'Maximum percentage chance to hit with regular melee/ranged'),
	(1, 'Combat:MaxFlurryHits', '2', 'Maximum number of extra hits from flurry'),
	(1, 'Combat:MaxRampageTargets', '3', 'Maximum number of people hit with rampage'),
	(1, 'Combat:MeleeCritDifficulty', '8900', 'Value against which is rolled to check if a melee crit is triggered. Lower is easier'),
	(1, 'Combat:MeleePush', 'true', 'Enable melee push'),
	(1, 'Combat:MeleePushChance', '25', 'NPC chance the target will be pushed. Made up, 100 actually isn\'t that bad'),
	(1, 'Combat:MinChancetoHit', '75.0000000000000', 'Minimum percentage chance to hit with regular melee/ranged'),
	(1, 'Combat:MinHastedDelay', '400', 'Minimum hasted combat delay'),
	(1, 'Combat:MinRangedAttackDist', '25', 'Minimum Distance to use Ranged Attacks'),
	(1, 'Combat:MiscACSoftcapReturn', '0.3000000119209', 'If OldACSoftcapRules true/false: unspecified classes armorclass softcap increase-factor'),
	(1, 'Combat:MonkACBonusWeight', '15', 'Usually, a monk under this weight threshold gets an AC bonus'),
	(1, 'Combat:MonkACSoftcap', '120', 'If OldACSoftcapRules is true: armorclass softcap for monks'),
	(1, 'Combat:NPCACFactor', '2.2500000000000', 'If UseIntervalAC is enabled, the armor class for NPC is divided by this value'),
	(1, 'Combat:NPCAssistCap', '5', 'Maximum number of NPC that will assist another NPC at once'),
	(1, 'Combat:NPCAssistCapTimer', '6000', 'Time a NPC will take to clear assist aggro cap space (milliseconds)'),
	(1, 'Combat:NPCBashKickLevel', '6', 'The level that NPCcan KICK/BASH'),
	(1, 'Combat:NPCBonusHitChance', '26.0000000000000', 'Bonus chance to hit for NPC'),
	(1, 'Combat:NPCCanCrit', 'false', 'Setting whether an NPC can land critical hits'),
	(1, 'Combat:NPCFlurryChance', '20', 'Chance for NPC to flurry'),
	(1, 'Combat:OldACSoftcapRules', 'false', 'Setting if the old softcap values should be used'),
	(1, 'Combat:OneProcPerWeapon', 'true', 'If enabled, One proc per weapon per round'),
	(1, 'Combat:PalShdACSoftcapReturn', '0.3226000070572', 'SHD/PAL armorclass softcap increase-factor'),
	(1, 'Combat:PetAttackMagicLevel', '11', 'Level at which pets can cause magic damage'),
	(1, 'Combat:PetBaseCritChance', '0', 'Pet base crit chance'),
	(1, 'Combat:PlateACSoftcap', '300', 'If OldACSoftcapRules is true: armorclass softcap for plate armor'),
	(1, 'Combat:ProcDexDivideBy', '11000.0000000000000', 'Divisor for the probability of a proc increased by dexterity'),
	(1, 'Combat:ProcPerMinDexContrib', '0.0750000029802', 'Increases the probability of a proc increased by DEX by the value indicated'),
	(1, 'Combat:ProjectileDmgOnImpact', 'true', 'If enabled, projectiles (i.e. arrows) will hit on impact, instead of instantly'),
	(1, 'Combat:QuiverHasteCap', '1000', 'Quiver haste cap 1000 on live for a while, currently 700 on live'),
	(1, 'Combat:RampageHitsTarget', 'false', 'Rampage will hit the target if it still has targets left'),
	(1, 'Combat:RogShmBstBerACSoftcapReturn', '0.2500000000000', 'ROG/SHM/BST/BER softcap increase-factor'),
	(1, 'Combat:SneakPullAssistRange', '400', 'Modified range of assist for sneak pull'),
	(1, 'Combat:SoftcapFactor', '1.8799999952316', 'When UseIntervalAC is enabled, the softcap for mitigation capability is multiplied by this value'),
	(1, 'Combat:SpecialAttackACBonus', '15', 'Percent amount of damage per AC gained for certain special attacks (damage = AC*SpecialAttackACBonus/100)'),
	(1, 'Combat:TauntOverLevel', 'true', 'Allows you to taunt NPC\'s over warriors level'),
	(1, 'Combat:TauntSkillFalloff', '0.3300000131130', 'For every taunt skill point that\'s not maxed you lose this percentage chance to taunt'),
	(1, 'Combat:ThrowingCritDifficulty', '1100', 'Value against which is rolled to check if a throwing crit is triggered. Lower is easier'),
	(1, 'Combat:UseExtendedPoisonProcs', 'FALSE', 'Allow old school poisons to last until characrer zones, at a lower proc rate'),
	(1, 'Combat:UseIntervalAC', 'true', 'Switch whether bonuses, armour class, multipliers, classes and caps should be considered in the calculation of damage values'),
	(1, 'Combat:UseLiveCombatRounds', 'true', 'Turn this false if you don\'t want to worry about fixing up combat rounds for NPCs'),
	(1, 'Combat:UseNPCDamageClassLevelMods', 'true', 'Uses GetClassLevelDamageMod calc in npc_scale_manager'),
	(1, 'Combat:UseOldDamageIntervalRules', 'true', 'Use old damage formulas for everything'),
	(1, 'Combat:UseRevampHandToHand', 'false', 'Use h2h revamped dmg/delays I believe this was implemented during SoF'),
	(1, 'Combat:WarACSoftcapReturn', '0.3447999954224', 'WAR armorclass softcap increase-factor'),
	(1, 'Combat:WarriorACSoftcapReturn', '0.4499999880791', 'If OldACSoftcapRules: warrior armorclass softcap increase-factor'),
	(1, 'Combat:WeaponSkillFalloff', '0.3300000131130', 'For every weapon skill point that\'s not maxed you lose this percentage of hit'),
	(1, 'Console:SessionTimeOut', '600000', 'Amount of time in ms for the console session to time out'),
	(1, 'DynamicZone:ClientRemovalDelayMS', '60000', 'Delay (milliseconds) until a client is teleported out of dynamic zone after being removed as member'),
	(1, 'DynamicZone:EmptyShutdownDelaySeconds', '1500', 'Seconds to set dynamic zone instance expiration if early shutdown enabled'),
	(1, 'DynamicZone:EmptyShutdownEnabled', 'true', 'Enable early instance shutdown for dynamic zones that have no members'),
	(1, 'DynamicZone:EnableInDynamicZoneStatus', 'false', 'Enables the \'In Dynamic Zone\' member status in dynamic zone window. If false (live-like) players inside the dynamic zone will show as \'Online\''),
	(1, 'DynamicZone:WorldProcessRate', '6000', 'Timer interval (milliseconds) that systems check their dynamic zone states'),
	(1, 'EventLog:RecordBuyFromMerchant', 'false', 'Record purchases by a player from an NPC merchant in eventlog table'),
	(1, 'EventLog:RecordSellToMerchant', 'true', 'Record sales from a player to an NPC merchant in eventlog table'),
	(1, 'Expansion:CurrentExpansion', '-1', 'The current expansion enabled for the server [-1 = ALL, 0 = Classic, 1 = Kunark etc.]'),
	(1, 'Expedition:AlwaysNotifyNewLeaderOnChange', 'false', 'Always notify clients when made expedition leader. If false (live-like) new leaders are only notified when made leader via /dzmakeleader'),
	(1, 'Expedition:ChooseLeaderCooldownTime', '2000', 'Cooldown time (milliseconds) between choosing a new leader for automatic leader changes'),
	(1, 'Expedition:LockoutDurationMultiplier', '1.0000000000000', 'Multiplies lockout duration by this value when new lockouts are added'),
	(1, 'Expedition:MinStatusToBypassPlayerCountRequirements', '80', 'Minimum GM status to bypass minimum player requirements for Expedition creation'),
	(1, 'Faction:AllyFactionMinimum', '1100', 'Minimum faction for ally'),
	(1, 'Faction:AmiablyFactionMinimum', '100', 'Minimum faction for amiably'),
	(1, 'Faction:ApprehensivelyFactionMinimum', '-100', 'Minimum faction for apprehensively'),
	(1, 'Faction:DubiouslyFactionMinimum', '-500', 'Minimum faction for dubiously'),
	(1, 'Faction:IndifferentlyFactionMinimum', '0', 'Minimum faction for indifferently'),
	(1, 'Faction:KindlyFactionMinimum', '500', 'Minimum faction for kindly'),
	(1, 'Faction:ThreateninglyFactionMinimum', '-750', 'Minimum faction for threateningly'),
	(1, 'Faction:WarmlyFactionMinimum', '750', 'Minimum faction for warmly'),
	(1, 'GM:MinStatusToBypassLockedServer', '100', 'Players >= this status can log in to the server even when it is locked'),
	(1, 'GM:MinStatusToLevelTarget', '100', 'Minimum required status to set the level of a player'),
	(1, 'GM:MinStatusToSummonItem', '250', 'Minimum required status to summon items'),
	(1, 'GM:MinStatusToZoneAnywhere', '250', 'Minimum required status to zone anywhere'),
	(1, 'Guild:PlayerCreationAllowed', 'false', 'Allow players to create a guild using the window in Underfoot+'),
	(1, 'Guild:PlayerCreationLimit', '1', 'Only allow use of the UF+ window if the account has < than this number of guild leaders on it'),
	(1, 'Guild:PlayerCreationRequiredLevel', '1', 'Required level of the player attempting to create the guild'),
	(1, 'Guild:PlayerCreationRequiredStatus', '0', 'Required status to create a guild'),
	(1, 'Guild:PlayerCreationRequiredTime', '0', 'Time needed online on the account to create a guild (in minutes)'),
	(1, 'HotReload:QuestsAutoReloadGlobalScripts', 'FALSE', 'When a quest, plugin, or global script changes, auto reload.'),
	(1, 'HotReload:QuestsRepopWhenPlayersNotInCombat', 'TRUE', 'When a hot reload is triggered, the zone will repop when no clients are in combat'),
	(1, 'HotReload:QuestsRepopWithReload', 'TRUE', 'When a hot reload is triggered, the zone will repop'),
	(1, 'HotReload:QuestsResetTimersWithReload', 'TRUE', 'When a hot reload is triggered, quest timers will be reset'),
	(1, 'Instances:GuildHallExpirationDays', '90', 'Amount of days before a Guild Hall instance expires'),
	(1, 'Instances:RecycleInstanceIds', 'TRUE', 'Setting whether free instance IDs should be recycled to prevent them from gradually running out at 32k'),
	(1, 'Instances:ReservedInstances', '30', 'Number of instance IDs which are reserved for globals. This value should not be changed while a server is running'),
	(1, 'Inventory:AllowAnyWeaponTransformation', 'false', 'Weapons can use any weapon transformation'),
	(1, 'Inventory:DeleteTransformationMold', 'true', 'False if you want mold to last forever'),
	(1, 'Inventory:EnforceAugmentRestriction', 'true', 'Forces augment slot restrictions'),
	(1, 'Inventory:EnforceAugmentUsability', 'true', 'Forces augmented item usability'),
	(1, 'Inventory:EnforceAugmentWear', 'true', 'Forces augment wear slot validation'),
	(1, 'Inventory:TransformSummonedBags', 'false', 'Transforms summoned bags into disenchanted ones instead of deleting'),
	(1, 'Logging:PrintFileFunctionAndLine', 'FALSE', 'Ex: [World Server] [net.cpp::main:309] Loading variables...'),
	(1, 'Mail:EnableMailSystem', 'true', 'Setting whether the mail system is activated. If false, client won\'t bring up the Mail window'),
	(1, 'Mail:ExpireRead', '31536000', 'Setting when read mails expire. 31536000=1 Year. Set to -1 for never'),
	(1, 'Mail:ExpireTrash', '0', 'Setting when the mail trash is emptied. Time in seconds. 0 will delete all messages in the trash when the mailserver starts'),
	(1, 'Mail:ExpireUnread', '31536000', 'Setting when unread mails expire. 31536000=1 Year. Set to -1 for never'),
	(1, 'Map:DistanceCanTravelBeforeAdjustment', '10.0000000000000', 'Distance a mob can path before FixZ is called, depends on FixZWhenPathing'),
	(1, 'Map:FindBestZHeightAdjust', '1', 'Adds this to the current Z before seeking the best Z position'),
	(1, 'Map:FixPathingZMaxDeltaSendTo', '30.0000000000000', 'At runtime in SendTo: maximum change in Z to allow the BestZ code to apply'),
	(1, 'Map:FixPathingZOnSendTo', 'true', 'Try to repair Z coordinates in the SendTo routine as well'),
	(1, 'Map:FixZWhenPathing', 'true', 'Automatically fix NPC Z coordinates when moving/pathing/engaged (Far less CPU intensive than its predecessor)'),
	(1, 'Map:MobZVisualDebug', 'false', 'Displays spell effects determining whether or not NPC is hitting Best Z calcs (blue for hit, red for miss)'),
	(1, 'Merchant:AllowCorpse', 'FALSE', 'Setting whether dealers leave a corpse behind '),
	(1, 'Merchant:BuyCostMod', '0.9499999880791', 'Modifier for NPC buy price'),
	(1, 'Merchant:ChaBonusMod', '3.4500000476837', 'Determines CHA cap, from 104 CHA. 3.45 is 132 CHA at apprehensive. 0.34 is 400 CHA at apprehensive'),
	(1, 'Merchant:ChaPenaltyMod', '1.5199999809265', 'Determines CHA bottom, up to 102 CHA. 1.52 is 37 CHA at apprehensive. 0.98 is 0 CHA at apprehensive'),
	(1, 'Merchant:EnableAltCurrencySell', 'true', 'Enables the ability to resell items to alternate currency merchants'),
	(1, 'Merchant:PriceBonusPct', '4', 'Determines maximum price bonus from having good faction/CHA. Value is a percent'),
	(1, 'Merchant:PricePenaltyPct', '4', 'Determines maximum price penalty from having bad faction/CHA. Value is a percent'),
	(1, 'Merchant:SellCostMod', '1.0499999523163', 'Modifier for NPC sell price'),
	(1, 'Merchant:UsePriceMod', 'true', 'Use faction/charisma price modifiers'),
	(1, 'Mercs:AggroRadius', '100', 'Determines the distance from which a merc will aggro group member\'s target(also used to determine the distance at which a healer merc will begin healing a group member)'),
	(1, 'Mercs:AggroRadiusPuller', '25', 'Determines the distance from which a merc will aggro group member\'s target, if they have the group role of puller (also used to determine the distance at which a healer merc will begin healing a group member, if they have the group role of puller)'),
	(1, 'Mercs:AllowMercs', 'false', 'Allow the use of mercs'),
	(1, 'Mercs:AllowMercSuspendInCombat', 'true', 'Allow merc suspend in combat'),
	(1, 'Mercs:ChargeMercPurchaseCost', 'false', 'Turns Mercenary purchase costs on or off'),
	(1, 'Mercs:ChargeMercUpkeepCost', 'false', 'Turns Mercenary upkeep costs on or off'),
	(1, 'Mercs:ResurrectRadius', '50', 'Determines the distance from which a healer merc will attempt to resurrect a group member\'s corpse'),
	(1, 'Mercs:ScaleRate', '100', 'Merc scale factor'),
	(1, 'Mercs:SuspendIntervalMS', '10000', 'Time interval for merc suspend (milliseconds)'),
	(1, 'Mercs:SuspendIntervalS', '10', 'Time interval for merc suspend command (seconds)'),
	(1, 'Mercs:UpkeepIntervalMS', '180000', 'Time interval for merc upkeep (milliseconds)'),
	(1, 'Network:ClientDataRate', '0', 'KB / sec, 0.0 disabled'),
	(1, 'Network:CompressZoneStream', 'FALSE', 'Setting whether the zone stream should be compressed for transmission'),
	(1, 'Network:ResendDelayBaseMS', '100', 'Base delay for resending data in EQStreamManager (milliseconds)'),
	(1, 'Network:ResendDelayFactor', '1.5000000000000', 'Multiplier for the base delay when resending data in EQStreamManager'),
	(1, 'Network:ResendDelayMaxMS', '5000', 'Maximum timespan between two send retries (milliseconds)'),
	(1, 'Network:ResendDelayMinMS', '100', 'Minimum timespan between two send retries (milliseconds)'),
	(1, 'NPC:AnimalsOpenDoors', 'false', 'Determines or not whether animals open doors or not when they approach them'),
	(1, 'NPC:BuffFriends', 'true', 'Setting whether NPC should buff other NPC'),
	(1, 'NPC:CorpseUnlockTimer', '150000', 'Time after which corpses are unlocked for everyone to loot (milliseconds)'),
	(1, 'NPC:EmptyNPCCorpseDecayTimeMS', '6000', 'NPC corpse decay time, if no items are left on the corpse (milliseconds)'),
	(1, 'NPC:EnableMeritBasedFaction', 'false', 'If set to true, faction will be given in the same way as experience (solo/group/raid)'),
	(1, 'NPC:EnableNPCQuestJournal', 'true', 'Setting whether the NPC Quest Journal is active'),
	(1, 'NPC:LastFightingDelayMovingMax', '20000', 'Maximum time before mob goes home after all aggro loss (milliseconds)'),
	(1, 'NPC:LastFightingDelayMovingMin', '10000', 'Minimum time before mob goes home after all aggro loss (milliseconds)'),
	(1, 'NPC:LiveLikeEnrage', 'false', 'If set to true then only player controlled pets will enrage'),
	(1, 'NPC:MajorNPCCorpseDecayTimeMS', '1500000', 'NPC corpse decay time, if NPC equal or greater than level 55 (milliseconds)'),
	(1, 'NPC:MinorNPCCorpseDecayTimeMS', '450000', 'NPC corpse decay time, if NPC below level 55 (milliseconds)'),
	(1, 'NPC:NewLevelScaling', 'true', 'Better level scaling, use old if new formulas would break your server'),
	(1, 'NPC:NPCGateDistanceBind', '75', 'Distance from bind before NPC will attempt to gate'),
	(1, 'NPC:NPCGateNearBind', 'false', 'Will NPC attempt to gate when near bind location?'),
	(1, 'NPC:NPCGatePercent', '5', ' Percentage at which the NPC Will attempt to gate at'),
	(1, 'NPC:NPCHealOnGate', 'true', 'Will the NPC Heal on Gate'),
	(1, 'NPC:NPCHealOnGateAmount', '25.0000000000000', 'How much the NPC will heal on gate if enabled'),
	(1, 'NPC:NPCToNPCAggroTimerMax', '6000', 'Maximum time span after which one NPC aggro another NPC (milliseconds)'),
	(1, 'NPC:NPCToNPCAggroTimerMin', '500', 'Minimum time span after which one NPC aggro another NPC (milliseconds)'),
	(1, 'NPC:OOCRegen', '1', 'Enable out-of-combat regeneration for NPC'),
	(1, 'NPC:ReturnNonQuestNoDropItems', 'true', 'Returns NO DROP items on NPC that don\'t have an EVENT_TRADE sub in their script'),
	(1, 'NPC:SayPauseTimeInSec', '10', 'Time span in which an NPC pauses his movement after a Say event without aggro (seconds)'),
	(1, 'NPC:SmartLastFightingDelayMoving', 'true', 'When true, mobs that started going home previously will do so again immediately if still on FD hate list'),
	(1, 'NPC:StartEnrageValue', '9', ' Percentage HP that an NPC will begin to enrage'),
	(1, 'NPC:UseBaneDamage', 'false', 'If NPCs can\'t inherently hit the target we don\'t add bane/magic dmg which isn\'t exactly the same as PCs'),
	(1, 'NPC:UseClassAsLastName', 'true', 'Uses class archetype as LastName for NPC with none'),
	(1, 'NPC:UseItemBonusesForNonPets', 'true', 'Switch whether item bonuses should be used for NPCs who are not pets'),
	(1, 'NPC:UseMeditateBasedManaRegen', 'FALSE', 'Based NPC ooc regen on Meditate skill'),
	(1, 'Pathing:Fear', 'true', 'Enable pathing for fear'),
	(1, 'Pathing:Find', 'false', 'Enable pathing for FindPerson requests from the client'),
	(1, 'Pathing:MaxNavmeshNodes', '4092', 'Maximum navmesh nodes in a traversable path'),
	(1, 'Pathing:NavmeshStepSize', '100.0f', 'Step size for the movement manager'),
	(1, 'Pathing:ShortMovementUpdateRange', '600.0f', 'Range for short movement updates'),
	(1, 'Pets:AttackCommandRange', '250.0000000000000', 'Range at which a pet will respond to attack commands'),
	(1, 'Pets:CanTakeNoDrop', 'false', 'Setting whether anyone can give no-drop items to pets'),
	(1, 'Pets:LivelikeBreakCharmOnInvis', 'true', 'Default: true will break charm on any type of invis (hide/ivu/iva/etc) false will only break if the pet can not see you (ex. you have an undead pet and cast IVU'),
	(1, 'Pets:PetPowerLevelCap', '10.0000000000000', 'Maximum number of levels a player pet can go up with pet power'),
	(1, 'Pets:UnTargetableSwarmPet', 'false', 'Setting whether swarm pets should be targetable'),
	(1, 'QueryServ:PlayerDropItems', 'false', 'Log player dropping items'),
	(1, 'QueryServ:PlayerLogAAPurchases', 'false', 'Log player AA purchases'),
	(1, 'QueryServ:PlayerLogAARate', 'false', 'Log player AA experience rates'),
	(1, 'QueryServ:PlayerLogAlternateCurrencyTransactions', 'false', 'Log player alternate currency transactions'),
	(1, 'QueryServ:PlayerLogChat', 'false', 'Log player chat'),
	(1, 'QueryServ:PlayerLogConnectDisconnect', 'false', 'Logs player connect/disconnect state'),
	(1, 'QueryServ:PlayerLogDeaths', 'false', 'Log player deaths'),
	(1, 'QueryServ:PlayerLogDeletes', 'true', 'Log player deletes'),
	(1, 'QueryServ:PlayerLogHandins', 'true', 'Log player hand ins'),
	(1, 'QueryServ:PlayerLogIssuedCommandes', 'false', 'Log player issued commands'),
	(1, 'QueryServ:PlayerLogLevels', 'false', 'Log player leveling/deleveling'),
	(1, 'QueryServ:PlayerLogMerchantTransactions', 'true', 'Log merchant transactions'),
	(1, 'QueryServ:PlayerLogMoves', 'false', 'Log player moves'),
	(1, 'QueryServ:PlayerLogNPCKills', 'false', 'Log player NPC kills'),
	(1, 'QueryServ:PlayerLogQGlobalUpdate', 'false', 'Log player QGlobal updates'),
	(1, 'QueryServ:PlayerLogTaskUpdates', 'false', 'Log player Task updates'),
	(1, 'QueryServ:PlayerLogTrades', 'true', 'Log player trades'),
	(1, 'QueryServ:PlayerLogTradeSkillEvents', 'false', 'Log player tradeskill transactions'),
	(1, 'QueryServ:PlayerLogZone', 'false', 'Log player zone events'),
	(1, 'Range:Anims', '600', 'The packet range in which begin cast messages are sent'),
	(1, 'Range:BeginCast', '200', 'The packet range in which begin cast messages are sent'),
	(1, 'Range:ClientPositionUpdates', '600', 'Distance in which the own changed position is communicated to other clients'),
	(1, 'Range:CriticalDamage', '150', 'The packet range in which critical hit messages are sent'),
	(1, 'Range:DamageMessages', '150', 'The packet range in which damage messages are sent (non-crit)'),
	(1, 'Range:Emote', '150', 'The packet range in which emote messages are sent\''),
	(1, 'Range:MobCloseScanDistance', '600', 'Close scan distance'),
	(1, 'Range:Say', '150', 'The range that is required before /say or hail messages will work to an NPC'),
	(1, 'Range:SongMessages', '225', 'The packet range in which song messages are sent'),
	(1, 'Range:SpellMessages', '225', 'The packet range in which spell damage messages are sent'),
	(1, 'Range:SpellParticles', '500', 'The packet range in which spell particles are sent'),
	(1, 'Skills:MaxTradeskillSearchSkillDiff', '50', 'The maximum difference in skill between the trivial of an item and the skill of the player if the trivial is higher than the skill. Recipes that have not been learnt or made at least once via the Experiment mode will be removed from searches based on this criteria.'),
	(1, 'Skills:MaxTrainSpecializations', '50', 'Maximum level a GM trainer will train casting specializations'),
	(1, 'Skills:MaxTrainTradeskills', '21', 'Highest level for trading skills that can be learnt by the trainer'),
	(1, 'Skills:RequireTomeHandin', 'FALSE', 'Disable click-to-learn and force hand in to Guild Master'),
	(1, 'Skills:SelfLanguageLearning', 'true', 'Enabling self-learning of languages'),
	(1, 'Skills:SenseHeadingStartValue', '1', 'Start value of sense heading skill'),
	(1, 'Skills:SwimmingStartValue', '1', 'Start value of swimming skill'),
	(1, 'Skills:TrainSenseHeading', 'true', 'Switch whether SenseHeading is trained by use'),
	(1, 'Skills:UseLimitTradeskillSearchSkillDiff', 'true', 'Enables the limit for the maximum difference between trivial and skill for recipe searches and favorites'),
	(1, 'Spells:AdditiveBonusWornType', '0', 'Calc worn bonuses to add together (instead of taking highest) if set to THIS worn type. (2=Will covert live items automatically)'),
	(1, 'Spells:AI_EngagedBeneficialOtherChance', '25', 'Chance during second AI Cast check to do a beneficial spell on others'),
	(1, 'Spells:AI_EngagedBeneficialSelfChance', '100', 'Chance during first AI Cast check to do a beneficial spell on self'),
	(1, 'Spells:AI_EngagedDetrimentalChance', '20', 'Chance during third AI Cast check to do a determental spell on others'),
	(1, 'Spells:AI_EngagedNoSpellMaxRecast', '1000', 'AI spell recast time check when no spell is cast engaged. Mmaximum time in random (milliseconds)'),
	(1, 'Spells:AI_EngagedNoSpellMinRecast', '500', 'AI spell recast time check when no spell is cast while engaged. Min time in random (milliseconds)'),
	(1, 'Spells:AI_HealHPPct', '50', 'Hitpoint percentage at which NPC starts healing when max_hp of the spell is not set (inside and outside combat)'),
	(1, 'Spells:AI_IdleBeneficialChance', '100', 'Chance while idle to do a beneficial spell on self or others'),
	(1, 'Spells:AI_IdleNoSpellMaxRecast', '60000', 'AI spell recast time check when no spell is cast while chasing target. Maximum time in random (milliseconds)'),
	(1, 'Spells:AI_IdleNoSpellMinRecast', '6000', 'AI spell recast time check when no spell is cast while idle. Mmin time in random (milliseconds)'),
	(1, 'Spells:AI_PursueDetrimentalChance', '90', 'Chance while chasing target to cast a detrimental spell'),
	(1, 'Spells:AI_PursueNoSpellMaxRecast', '2000', 'AI spell recast time check when no spell is cast while chasing target. Maximum time in random (milliseconds)'),
	(1, 'Spells:AI_PursueNoSpellMinRecast', '500', 'AI spell recast time check when no spell is cast while chasing target. Mmin time in random (milliseconds)'),
	(1, 'Spells:AI_SpellCastFinishedFailRecast', '800', 'AI spell recast time  when an spell is cast but fails, ie if stunned (milliseconds)'),
	(1, 'Spells:AllowDoubleInvis', 'false', 'Allows you to cast invisibility spells on a player that is already invisible'),
	(1, 'Spells:AllowItemTGB', 'false', 'Target group buff (/tgb) doesn\'t work with items on live, custom servers want it though'),
	(1, 'Spells:AllowSpellMemorizeFromItem', 'false', 'Allows players to memorize spells by right-clicking spell scrolls'),
	(1, 'Spells:AlwaysSendTargetsBuffs', 'true', 'Ignore Leadership Alternate Abilities level if true'),
	(1, 'Spells:AOEMaxTargets', '0', 'Max number of targets a Targeted AOE spell can cast on. Set to 0 for no limit.'),
	(1, 'Spells:AvgSpellProcsPerMinute', '6.0000000000000', 'Adjust rate for sympathetic spell procs'),
	(1, 'Spells:BaseCritChance', '0', 'Base percentage chance that everyone has to crit a spell'),
	(1, 'Spells:BaseCritRatio', '100', 'Base percentage bonus to damage on a successful spell crit. 100=2xdamage'),
	(1, 'Spells:BaseImmunityLevel', '55', 'The level that targets start to be immune to stun, fear and mez spells with a maximum level of 0'),
	(1, 'Spells:BuffLevelRestrictions', 'false', 'Buffs will not land on low level toons like live'),
	(1, 'Spells:CazicTouchTargetsPetOwner', 'true', 'If True, causes Cazic Touch to swap targets from pet to pet owner if a pet is tanking.'),
	(1, 'Spells:CharismaCharmDuration', 'true', 'Allow CHA resist mod to extend charm duration'),
	(1, 'Spells:CharismaEffectiveness', '10', 'Determines how much resist modification charisma applies to charm/pacify checks. Default 10 CHA = -1 resist mod'),
	(1, 'Spells:CharismaEffectivenessCap', '200', 'Determines how much resist modification charisma applies to charm/pacify checks. Default 10 CHA = -1 resist mod'),
	(1, 'Spells:CharmBreakCheckChance', '10', 'Determines chance for a charm break check to occur each buff tick'),
	(1, 'Spells:CharmDisablesSpecialAbilities', 'FALSE', 'When charm is cast on an NPC, strip their special abilities'),
	(1, 'Spells:DeathSaveCharismaMod', '3', 'Determines how much charisma effects chance of death save firing'),
	(1, 'Spells:DivineInterventionHeal', '8000', 'Divine intervention heal amount'),
	(1, 'Spells:EnableBlockedBuffs', 'true', 'Allow blocked spells'),
	(1, 'Spells:EnableSpellBuckets', 'false', 'If enabled, spells check the spell_buckets table and compare character data from their data buckets before allowing the spell to scribe with scribespells/traindiscs'),
	(1, 'Spells:EnableSpellGlobals', 'false', 'If enabled, spells check the spell_globals table and compare character data from their quest globals before allowing the spell to scribe with scribespells/traindiscs'),
	(1, 'Spells:FearBreakCheckChance', '70', 'Determines chance for a fear break check to occur each buff tick'),
	(1, 'Spells:FlatItemExtraSpellAmt', 'false', 'Allow SpellDmg stat to affect all spells, regardless of cast time/cooldown/etc'),
	(1, 'Spells:FocusCombatProcs', 'false', 'Allow all combat procs to receive focus effects'),
	(1, 'Spells:FRProjectileItem_NPC', '80684', 'Item id for NPC Fire \'spell projectile\''),
	(1, 'Spells:FRProjectileItem_SOF', '80684', 'Item id for SOF clients for Fire \'spell projectile\''),
	(1, 'Spells:FRProjectileItem_Titanium', '80684', 'Item id for Titanium clients for Fire \'spell projectile\''),
	(1, 'Spells:IgnoreSpellDmgLvlRestriction', 'true', 'Ignore the 5 level spread on applying SpellDmg'),
	(1, 'Spells:InvisRequiresGroup', 'false', 'Invis requires the the target to be in group.'),
	(1, 'Spells:July242002PetResists', 'true', 'Enable Pets using PCs resist change from July 24 2002'),
	(1, 'Spells:Jun182014HundredHandsRevamp', 'false', 'This should be true for if you import a spell file newer than June 18, 2014'),
	(1, 'Spells:LiveLikeFocusEffects', 'true', 'Determines whether specific healing, dmg and mana reduction focuses are randomized'),
	(1, 'Spells:MaxBuffSlotsNPC', '55', 'Maximum number of NPC buff slots. The default value is the limit of the Titanium client'),
	(1, 'Spells:MaxDiscSlotsNPC', '1', 'Maximum number of NPC disc slots. NPC don\'t have discs, so it should be 0'),
	(1, 'Spells:MaxSongSlotsNPC', '10', 'Maximum number of NPC song slots. NPC don\'t have songs, so it should be 0'),
	(1, 'Spells:MaxTotalSlotsNPC', '66', 'Maximum total of NPC slots. The default value is the limit of the Titanium client'),
	(1, 'Spells:MaxTotalSlotsPET', '25', 'Maximum total of pet slots. The default value is the limit of the Titanium client'),
	(1, 'Spells:NPCIgnoreBaseImmunity', 'true', 'Whether or not NPC get to ignore the BaseImmunityLevel for their spells'),
	(1, 'Spells:NPCInnateProcOverride', 'true', 'NPC innate procs override the target type to single target'),
	(1, 'Spells:NPCSpellPush', 'false', 'Enable spell push on NPCs'),
	(1, 'Spells:NPC_UseFocusFromItems', 'false', 'Allow NPC to use most item derived focus effects'),
	(1, 'Spells:NPC_UseFocusFromSpells', 'true', 'Allow NPC to use most spell derived focus effects'),
	(1, 'Spells:OldRainTargets', 'false', 'Use old incorrectly implemented maximum targets for rains'),
	(1, 'Spells:PreNerfBardAEDoT', 'true', 'Allow bard AOE dots to damage targets when moving'),
	(1, 'Spells:PreventFactionWarOnCharmBreak', 'false', 'Enable spell interupts and dot removal on charm break to prevent faction wars.'),
	(1, 'Spells:ReflectMessagesClose', 'true', 'True (Live functionality) is for Reflect messages to show to players within close proximity. False shows just player reflecting'),
	(1, 'Spells:ReflectType', '1', 'Reflect type. 0=disabled, 1=single target player spells only, 2=all player spells, 3=all single target spells, 4=all spells'),
	(1, 'Spells:ResistFalloff', '67', 'Maximum that level that will adjust our resist chance based on level modifiers'),
	(1, 'Spells:RootBreakCheckChance', '70', 'Determines chance for a root break check to occur each buff tick'),
	(1, 'Spells:RootBreakFromSpells', '50', 'Chance for root to break when cast on'),
	(1, 'Spells:SacrificeItemID', '9963', 'Item ID of the item Sacrifice will return (defaults to an Essence Emerald)'),
	(1, 'Spells:SacrificeMaxLevel', '70', 'Last level the spell Sacrifice will work on'),
	(1, 'Spells:SacrificeMinLevel', '46', 'First level the spell Sacrifice will work on'),
	(1, 'Spells:SHDProcIDOffByOne', 'false', 'Pre June 2009 SHD spell procs were off by 1, they stopped doing this in June 2009 (UF+ spell files need this false)'),
	(1, 'Spells:SuccorFailChance', '1', 'Determines chance for a succor spell not to teleport an invidual player'),
	(1, 'Spells:SwarmPetTargetLock', 'true', 'Use old method of swarm pets target locking till target dies then despawning'),
	(1, 'Spells:TranslocateTimeLimit', '0', 'If not zero, time in seconds to accept a Translocate'),
	(1, 'Spells:UseAdditiveFocusFromWornSlot', 'false', 'Allows an additive focus effect to be calculated from worn slot'),
	(1, 'Spells:UseCHAScribeHack', 'false', 'ScribeSpells and TrainDiscs quest functions will ignore entries where field 12 is CHA'),
	(1, 'Spells:UseLiveSpellProjectileGFX', 'true', 'Use spell projectile graphics set in the spells_new table (player_1). Server must be using UF+ spell file'),
	(1, 'Spells:VirusSpreadDistance', '30', 'The distance a viral spell will jump to its next victim'),
	(1, 'Spells:WizCritChance', '0', 'Wizards crit chance, on top of BaseCritChance'),
	(1, 'Spells:WizCritLevel', '0', 'Level wizards first get spell crits'),
	(1, 'Spells:WizCritRatio', '0', 'Wizards crit bonus, on top of BaseCritRatio (should be 0 for Live-like)'),
	(1, 'TaskSystem:EnableTaskProximity', 'true', 'Enable task proximity system'),
	(1, 'TaskSystem:EnableTaskSystem', 'true', 'Globally enable or disable the Task system'),
	(1, 'TaskSystem:KeepOneRecordPerCompletedTask', 'true', 'Keep only one record per completed task'),
	(1, 'TaskSystem:PeriodicCheckTimer', '5', 'Seconds between checks for failed tasks. Also used by the \'Touch\' activity'),
	(1, 'TaskSystem:RecordCompletedOptionalActivities', 'false', 'Record completed optional activities'),
	(1, 'TaskSystem:RecordCompletedTasks', 'true', 'Record completed tasks'),
	(1, 'Watermap:CheckForWaterOnSendTo', 'false', 'Checks if a mob has moved into/out of water on SendTo'),
	(1, 'Watermap:CheckForWaterWhenFishing', 'true', 'Only lets a player fish near water (if a water map exists for the zone)'),
	(1, 'Watermap:FishingLineLength', '100.0000000000000', 'If water is more than this far below the player, it is considered too far to fish'),
	(1, 'Watermap:FishingLineStepSize', '1.0000000000000', 'Basic step size for fishing calc, too small and it will eat cpu, too large and it will miss potential water'),
	(1, 'Watermap:FishingRodLength', '30.0000000000000', 'How far in front of player water must be for fishing to work'),
	(1, 'World:AddMaxClientsPerIP', '3', 'Maximum number of clients allowed to connect per IP address if account status is < ExemptMaxClientsStatus. Default value: -1 (feature disabled)'),
	(1, 'World:AddMaxClientsStatus', '80', 'Accounts with status >= this rule will be allowed to use the amount of accounts defined in the AddMaxClientsPerIP. Default value: -1 (feature disabled)'),
	(1, 'World:ClearTempMerchantlist', 'false', 'Clears temp merchant items when world boots'),
	(1, 'World:EnableDevTools', 'true', 'Enable or Disable the Developer Tools globally (Most of the time you want this enabled)'),
	(1, 'World:EnableIPExemptions', 'false', 'If true, ip_exemptions table is used, if there is no entry for the IP it will default to RuleI(World, MaxClientsPerIP)'),
	(1, 'World:EnableReturnHomeButton', 'false', 'Setting whether the Return Home button should be active'),
	(1, 'World:EnableTutorialButton', 'false', 'Setting whether the Tutorial button should be active. At least in RoF2 you can always press the button, but it loses its effect'),
	(1, 'World:EnforceCharacterLimitAtLogin', 'FALSE', 'Enforce the limit for characters that are online at login'),
	(1, 'World:ExemptMaxClientsStatus', '80', 'Exempt accounts from the MaxClientsPerIP and AddMaxClientsStatus rules, if their status is >= this value. Default value: -1 (feature disabled)'),
	(1, 'World:ExpansionSettings', '0', 'Sets the expansion settings for the server, This is sent on login to world and affects client expansion settings. Defaults to all expansions enabled up to TSS, value is bitmask'),
	(1, 'World:FVNoDropFlag', '0', 'Sets the Firiona Vie settings on the client, allowing trading of no-drop items. 1=for all players, 2=for GM only'),
	(1, 'World:GMAccountIPList', 'false', 'Check IP list against GM accounts. This increases the security of GM accounts, e.g. if you only allow localhost \'127.0.0.1\' for GM accounts. Think carefully about what you enter!'),
	(1, 'World:GuildBankZoneID', '345', 'Zone ID of the guild bank'),
	(1, 'World:IPLimitDisconnectAll', 'true', 'Disconnect all current clients by IP if they go over the IP limit.  This should allow people to quickly reconnect in the case of dead sessions waiting to timeout'),
	(1, 'World:IsGMPetitionWindowEnabled', 'true', 'Setting whether the GM petition window is available'),
	(1, 'World:MaxClientsPerIP', '3', 'Maximum number of clients allowed to connect per IP address if account status is < AddMaxClientsStatus. Default value: -1 (feature disabled)'),
	(1, 'World:MaxClientsSetByStatus', 'false', 'If true, IP Limiting will be set to the status on the account as long as the status is > MaxClientsPerIP'),
	(1, 'World:MaxLevelForTutorial', '15', 'The highest level with which you can enter the tutorial'),
	(1, 'World:MinGMAntiHackStatus', '11', 'Minimum status to check against AntiHack list'),
	(1, 'World:MinOfflineTimeToReturnHome', '2147483647', 'Minimum offline time to activate the Return Home button. 21600 seconds is 6 Hours'),
	(1, 'World:PVPMinLevel', '0', 'Minimum level to pvp'),
	(1, 'World:PVPSettings', '0', 'Sets the PVP settings for the server. 1=Rallos Zek RuleSet, 2=Tallon/Vallon Zek Ruleset, 4=Sullon Zek Ruleset, 6=Discord Ruleset, anything above 6 is the Discord Ruleset without the no-drop restrictions removed. NOTE: edit IsAttackAllowed in Zone-table to accomodate for these rules'),
	(1, 'World:SoFStartZoneID', '-1', 'Sets the Starting Zone for SoF Clients separate from Titanium Clients (-1 is disabled)'),
	(1, 'World:StartZoneSameAsBindOnCreation', 'false', 'Should the start zone always be the same location as your bind?'),
	(1, 'World:TellQueueSize', '20', 'Maximum tell queue size'),
	(1, 'World:TitaniumStartZoneID', '-1', 'Sets the Starting Zone for Titanium Clients (-1 is disabled). Replaces the old method'),
	(1, 'World:TutorialZoneID', '22', 'Zone ID of the tutorial'),
	(1, 'World:UseBannedIPsTable', 'false', 'Toggle whether or not to check incoming client connections against the banned_ips table. Set this value to false to disable this feature'),
	(1, 'World:UseClientBasedExpansionSettings', 'FALSE', 'If true it will overrule World, ExpansionSettings and set someone\'s expansion based on the client they\'re using'),
	(1, 'World:ZoneAutobootTimeoutMS', '31536000000', 'Time out for automatic booting of zones in milliseconds'),
	(1, 'Zone:AutoShutdownDelay', '31536000000', 'How long a dynamic zone stays loaded while empty (milliseconds)'),
	(1, 'Zone:ClientLinkdeadMS', '45000', 'The time a client remains link dead on the server after a sudden disconnection (milliseconds)'),
	(1, 'Zone:EbonCrystalItemID', '40902', 'Item ID for Ebon Crystal'),
	(1, 'Zone:EnableLoggedOffReplenishments', 'false', '\'Replenish mana/hp/end if logged off for MinOfflineTimeToReplenishments'),
	(1, 'Zone:EnableShadowrest', 'true', 'Enables or disables the Shadowrest zone feature for player corpses. Default is turned on'),
	(1, 'Zone:EnableZoneControllerGlobals', 'true', 'Enables the ability to use quest globals with the zone controller NPC'),
	(1, 'Zone:GlobalLootMultiplier', '1', 'Sets Global Loot drop multiplier for database based drops, useful for double, triple loot etc'),
	(1, 'Zone:GraveyardTimeMS', '1200000', 'Time until a player corpse is moved to a zone\'s graveyard, if one is specified for the zone (milliseconds)'),
	(1, 'Zone:HotZoneBonus', '0.4000000059605', 'Value which is added to the experience multiplier. This also applies to AA experience.'),
	(1, 'Zone:KillProcessOnDynamicShutdown', 'TRUE', 'When process has booted a zone and has hit its zone shut down timer, it will hard kill the process to free memory back to the OS'),
	(1, 'Zone:LevelBasedEXPMods', 'true', 'Allows you to use the level_exp_mods table in consideration to your players experience hits'),
	(1, 'Zone:MinOfflineTimeToReplenishments', '21600', 'Minimum time a player must be offline before LoggedOffReplenishments becomes active (seconds)'),
	(1, 'Zone:PEQZoneDebuff1', '4454', 'First debuff casted by #peqzone Default is Cursed Keeper\'s Blight'),
	(1, 'Zone:PEQZoneDebuff2', '2209', 'Second debuff casted by #peqzone Default is Tendrils of Apathy'),
	(1, 'Zone:PEQZoneReuseTime', '300', 'Time between two uses of the #peqzone command (seconds)'),
	(1, 'Zone:RadiantCrystalItemID', '40903', 'Item ID for Radiant Crystal'),
	(1, 'Zone:SecondsBeforeIdle', '31557600', 'Seconds before IDLE_WHEN_EMPTY define kicks in'),
	(1, 'Zone:SpawnEventMin', '3', 'When strict is set in spawn_events, specifies the max EQ minutes into the trigger hour a spawn_event will fire. Going below 3 may cause the spawn_event to not fire.'),
	(1, 'Zone:UsePEQZoneDebuffs', 'false', 'Setting if the command #peqzone applies the defined debuffs'),
	(1, 'Zone:UseZoneController', 'false', 'Enables the ability to use persistent quest based zone controllers (zone_controller.pl/lua)'),
	(1, 'Zone:WeatherTimer', '600', 'Weather timer when no duration is available');
/*!40000 ALTER TABLE `rule_values` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
