-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.0.21-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             9.1.0.4867
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping structure for table peq.spawn_conditions
CREATE TABLE IF NOT EXISTS `spawn_conditions` (
  `zone` varchar(32) NOT NULL DEFAULT '',
  `id` mediumint(8) unsigned NOT NULL DEFAULT '1',
  `value` mediumint(9) NOT NULL DEFAULT '0',
  `onchange` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `name` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`zone`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table peq.spawn_conditions: ~129 rows (approximately)
/*!40000 ALTER TABLE `spawn_conditions` DISABLE KEYS */;
INSERT INTO `spawn_conditions` (`zone`, `id`, `value`, `onchange`, `name`) VALUES
	('burningwood', 2, 0, 2, 'Naxot'),
	('butcher', 1, 0, 2, 'Stormbreaker'),
	('butcher', 2, 0, 2, 'SirensBane'),
	('commons', 1, 1, 2, 'CommonsNightMobs'),
	('commons', 2, 0, 2, 'CommonsDayMobs'),
	('corathus', 1, 0, 2, 'CorStartEvent'),
	('corathus', 2, 1, 2, 'CorCourtyard'),
	('corathus', 3, 1, 2, 'CorSporeAreaTrash'),
	('corathus', 4, 1, 2, 'CorMinotaurAreaTrash'),
	('corathus', 5, 1, 2, 'CorClockworkAreaTrash'),
	('corathus', 6, 0, 2, 'CorSporeAreaTrashBossDead'),
	('corathus', 7, 0, 2, 'CorMinotaurAreaTrashBossDead'),
	('corathus', 8, 0, 2, 'CorClockworkAreaTrashBossDead'),
	('corathus', 9, 1, 2, 'CorSporeBoss'),
	('corathus', 10, 1, 2, 'CorMinotaurBoss'),
	('corathus', 11, 1, 2, 'CorClockworkSpiderBoss'),
	('corathus', 12, 1, 2, 'CorEventPhase3'),
	('dawnshroud', 1, 0, 2, 'Sambata'),
	('dawnshroud', 2, 1, 2, 'Rockhopper'),
	('eastwastes', 1, 0, 2, 'Night (Unused)'),
	('erudnext', 1, 0, 2, 'Sea_King'),
	('erudnext', 2, 0, 2, 'Golden_Maiden'),
	('erudsxing', 1, 0, 2, 'Sea-Golden'),
	('erudsxing', 2, 0, 2, 'Golden-Sea'),
	('everfrost', 1, 1, 2, 'EverfrostNight'),
	('everfrost', 2, 0, 2, 'EverfrostDay'),
	('fearplane', 1, 1, 2, 'Cazic_Spawned'),
	('fieldofbone', 1, 1, 2, 'FoBNight'),
	('fieldofbone', 2, 0, 2, 'FoBDay'),
	('firiona', 1, 1, 2, 'TrackerDay'),
	('firiona', 2, 2, 2, 'TrackerNight'),
	('firiona', 3, 0, 2, 'Maidens'),
	('freporte', 1, 1, 2, 'BarFreeportNight'),
	('freporte', 2, 0, 2, 'BarFreeportDay'),
	('freporte', 3, 0, 2, 'Stormbreaker'),
	('freporte', 4, 0, 2, 'SirensBane'),
	('greatdivide', 1, 1, 2, 'ColdainWar'),
	('guildlobby', 1, 1, 0, 'Time Keeper'),
	('hollowshade', 1, 1, 2, 'North_Owl'),
	('hollowshade', 2, 1, 2, 'North_Wolf'),
	('hollowshade', 3, 1, 2, 'North_Grimling'),
	('hollowshade', 4, 1, 2, 'East_Owl'),
	('hollowshade', 5, 1, 2, 'East_Wolf'),
	('hollowshade', 6, 1, 2, 'East_Grimling'),
	('hollowshade', 7, 1, 2, 'South_Owl'),
	('hollowshade', 8, 1, 2, 'South_Wolf'),
	('hollowshade', 9, 1, 2, 'South_Grimling'),
	('kaladimb', 1, 1, 2, 'FounySpawn'),
	('kithicor', 1, 2, 2, 'KithicorNight'),
	('kithicor', 2, 1, 2, 'KithicorDay'),
	('lakerathe', 1, 1, 2, 'LakeRatheDay'),
	('lakerathe', 2, 2, 2, 'LakeRatheNight'),
	('lfaydark', 1, 1, 2, 'lfaydarkNightMobs'),
	('lfaydark', 2, 0, 2, 'lfaydarkday'),
	('mischiefplane', 1, 1, 2, 'Mischief 1.0'),
	('mischiefplane', 2, 0, 2, 'Mischief 2.0'),
	('neriakb', 1, 1, 2, 'NeriakBNight'),
	('neriakb', 2, 0, 2, 'NeriakBDay'),
	('neriakc', 1, 1, 2, 'TaniSpawn'),
	('northkarana', 1, 1, 2, 'NKaranaNightMobs'),
	('northkarana', 2, 0, 2, 'NKaranaDayMobs'),
	('oasis', 1, 0, 2, 'Barrel_Barge'),
	('oasis', 2, 0, 2, 'Muckskimmer'),
	('oggok', 1, 1, 2, 'Gronk'),
	('oggok', 2, 0, 2, 'Ryn '),
	('oot', 1, 0, 2, 'StormSirens'),
	('oot', 2, 0, 2, 'SirensStorm'),
	('overthere', 1, 1, 2, 'DragoonNight'),
	('overthere', 2, 0, 2, 'DragoonDay'),
	('overthere', 3, 0, 2, 'Bloated_belly'),
	('poeartha', 1, 0, 2, 'poe_dust_event'),
	('poeartha', 2, 0, 2, 'poe_ stone_event'),
	('poearthb', 1, 1, 2, 'rathecouncil'),
	('pofire', 1, 0, 2, 'pofire_Fennin'),
	('pofire', 2, 1, 2, 'pofire_Fennin'),
	('pofire', 3, 0, 2, 'pofire_Guardian'),
	('poinnovation', 1, 0, 2, 'poiend'),
	('poinnovation', 2, 0, 2, 'poinendloot'),
	('potactics', 1, 1, 2, 'PoTactics Stampede Event'),
	('potimeb', 1, 0, 2, 'potimeb_phase5'),
	('potimeb', 2, 0, 2, 'potimeb_p3wave1'),
	('potimeb', 3, 0, 2, 'potimeb_p3wave2'),
	('potimeb', 4, 0, 2, 'potimeb_p3wave3'),
	('potimeb', 5, 0, 2, 'potimeb_p3wave4'),
	('potimeb', 6, 0, 2, 'potimeb_p3wave5'),
	('potimeb', 7, 0, 2, 'potimeb_p3wave6'),
	('potimeb', 8, 0, 2, 'potimeb_p3wave7'),
	('potimeb', 9, 0, 2, 'potimeb_p3wave8'),
	('potimeb', 10, 0, 2, 'potimeb_phase2'),
	('qcat', 1, 0, 2, 'CourierSpawn'),
	('qcat', 2, 1, 2, 'MalkaSpawn'),
	('qey2hh1', 1, 1, 2, 'WKaranaNightMobs'),
	('qey2hh1', 2, 0, 2, 'WKaranaDayMobs'),
	('qey2hh1', 3, 0, 2, 'WKaranaGuardTrigger'),
	('qeynos', 1, 1, 2, 'QeynosNight'),
	('qeynos', 2, 0, 2, 'QeynosDay'),
	('qeynos', 3, 0, 2, 'Sea_King'),
	('qeynos', 4, 0, 2, 'Golden_Maiden'),
	('qeynos2', 1, 1, 2, 'NorthQeynosNight'),
	('qeynos2', 2, 0, 2, 'NorthQeynosDay'),
	('qeytoqrg', 1, 1, 2, 'QeynosHillNight'),
	('qeytoqrg', 2, 0, 2, 'QeynosHillDay'),
	('rathemtn', 1, 0, 2, 'Zephyl'),
	('rathemtn', 2, 1, 2, 'Hasten'),
	('riwwi', 1, 0, 2, 'stonemites'),
	('riwwi', 2, 0, 2, 'nightwatchman'),
	('sleeper', 1, 1, 2, 'Warders'),
	('sleeper', 2, 0, 2, 'Ancients'),
	('sncrematory', 1, 0, 2, 'named_trigger'),
	('snlair', 1, 0, 2, 'named_trigger'),
	('snlair', 2, 1, 1, 'event'),
	('snlair', 3, 0, 2, 'flagging'),
	('snplant', 1, 0, 2, ''),
	('snplant', 2, 0, 2, ''),
	('snpool', 1, 0, 2, ''),
	('soltemple', 1, 1, 2, 'SolTNight'),
	('soltemple', 2, 0, 2, 'SolTDay'),
	('steamfont', 1, 1, 2, 'Cargo'),
	('swampofnohope', 1, 1, 2, 'MysticDovan'),
	('swampofnohope', 2, 0, 2, 'CaptainNedar'),
	('thurgadinb', 1, 1, 2, 'ThurgbNight'),
	('thurgadinb', 2, 0, 2, 'ThurgbDay'),
	('timorous', 1, 0, 2, 'Maidens'),
	('timorous', 2, 0, 2, 'Barrel_Barge'),
	('timorous', 3, 0, 2, 'Muckskimmer'),
	('timorous', 4, 0, 2, 'Bloated_Belly'),
	('veeshan', 1, 0, 2, 'VeeshanOld'),
	('veeshan', 2, 1, 2, 'VeeshanNew'),
	('vxed', 1, 1, 2, 'Instance_Trigger');
/*!40000 ALTER TABLE `spawn_conditions` ENABLE KEYS */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
